package goua

// TODO: fix case

/*
#include "open62541.h"
*/
import "C"

//go:generate go run golang.org/x/tools/cmd/stringer@latest -type=StatusCode -linecomment
type StatusCode C.UA_StatusCode

const (
	/* These StatusCodes are manually generated. */
	StatusCode_InfoType_DataValue StatusCode = 0x00000400
	StatusCode_InfoBits_Overflow  StatusCode = 0x00000080

	StatusCode_Good                                                            StatusCode = 0x00000000 // The operation succeeded.
	StatusCode_Uncertain                                                       StatusCode = 0x40000000 // The operation was uncertain.
	StatusCode_Bad                                                             StatusCode = 0x80000000 // The operation failed.
	StatusCode_BadUnExpectedError                                              StatusCode = 0x80010000 // An unexpected error occurred.
	StatusCode_BadInternalError                                                StatusCode = 0x80020000 // An internal error occurred as a result of a programming or configuration error.
	StatusCode_BadOutOfMemory                                                  StatusCode = 0x80030000 // Not enough memory to complete the operation.
	StatusCode_BadResourceUnavailable                                          StatusCode = 0x80040000 // An operating system resource is not available.
	StatusCode_BadCommunicationError                                           StatusCode = 0x80050000 // A low level communication error occurred.
	StatusCode_BadEncodingError                                                StatusCode = 0x80060000 // Encoding halted because of invalid data in the objects being serialized.
	StatusCode_BadDecodingError                                                StatusCode = 0x80070000 // Decoding halted because of invalid data in the stream.
	StatusCode_BadEncodinglimitsExceeded                                       StatusCode = 0x80080000 // The message encoding/decoding limits imposed by the stack have been exceeded.
	StatusCode_BadRequestTooLarge                                              StatusCode = 0x80B80000 // The request message size exceeds limits set by the server.
	StatusCode_BadResponseTooLarge                                             StatusCode = 0x80B90000 // The response message size exceeds limits set by the client.
	StatusCode_BadUnknownResponse                                              StatusCode = 0x80090000 // An unrecognized response was received from the server.
	StatusCode_BadTimeout                                                      StatusCode = 0x800A0000 // The operation timed out.
	StatusCode_BadServiceUnsupported                                           StatusCode = 0x800B0000 // The server does not support the requested service.
	StatusCode_BadShutdown                                                     StatusCode = 0x800C0000 // The operation was cancelled because the application is shutting down.
	StatusCode_BadServerNotConnected                                           StatusCode = 0x800D0000 // The operation could not complete because the client is not connected to the server.
	StatusCode_BadServerHalted                                                 StatusCode = 0x800E0000 // The server has stopped and cannot process any requests.
	StatusCode_BadNothingToDo                                                  StatusCode = 0x800F0000 // No processing could be done because there was nothing to do.
	StatusCode_BadTooManyOperations                                            StatusCode = 0x80100000 // The request could not be processed because it specified too many operations.
	StatusCode_BadTooManyMonitoredItems                                        StatusCode = 0x80DB0000 // The request could not be processed because there are too many monitored items in the subscription.
	StatusCode_BadDataTypeIDUnknown                                            StatusCode = 0x80110000 // The extension object cannot be (de)serialized because the data type id is not recognized.
	StatusCode_BadCertificateInvalid                                           StatusCode = 0x80120000 // The certificate provided as a parameter is not valid.
	StatusCode_BadSecurityChecksFailed                                         StatusCode = 0x80130000 // An error occurred verifying security.
	StatusCode_BadCertificatePolicyCheckFailed                                 StatusCode = 0x81140000 // The certificate does not meet the requirements of the security policy.
	StatusCode_BadCertificateTimeInvalid                                       StatusCode = 0x80140000 // The certificate has expired or is not yet valid.
	StatusCode_BadCertificateIssuerTimeInvalid                                 StatusCode = 0x80150000 // An issuer certificate has expired or is not yet valid.
	StatusCode_BadCertificateHostNameInvalid                                   StatusCode = 0x80160000 // The HostName used to connect to a server does not match a HostName in the certificate.
	StatusCode_BadCertificateURIInvalid                                        StatusCode = 0x80170000 // The URI specified in the ApplicationDescription does not match the URI in the certificate.
	StatusCode_BadCertificateUseNotAllowed                                     StatusCode = 0x80180000 // The certificate may not be used for the requested operation.
	StatusCode_BadCertificateIssuerUseNotAllowed                               StatusCode = 0x80190000 // The issuer certificate may not be used for the requested operation.
	StatusCode_BadCertificateUntrusted                                         StatusCode = 0x801A0000 // The certificate is not trusted.
	StatusCode_BadCertificateRevocationUnknown                                 StatusCode = 0x801B0000 // It was not possible to determine if the certificate has been revoked.
	StatusCode_BadCertificateIssuerRevocationUnknown                           StatusCode = 0x801C0000 // It was not possible to determine if the issuer certificate has been revoked.
	StatusCode_BadCertificateRevoked                                           StatusCode = 0x801D0000 // The certificate has been revoked.
	StatusCode_BadCertificateIssuerRevoked                                     StatusCode = 0x801E0000 // The issuer certificate has been revoked.
	StatusCode_BadCertificateChainInComplete                                   StatusCode = 0x810D0000 // The certificate chain is incomplete.
	StatusCode_BadUserAccessDenied                                             StatusCode = 0x801F0000 // User does not have permission to perform the requested operation.
	StatusCode_BadIdentityTokenInvalid                                         StatusCode = 0x80200000 // The user identity token is not valid.
	StatusCode_BadIdentityTokenRejected                                        StatusCode = 0x80210000 // The user identity token is valid but the server has rejected it.
	StatusCode_BadSecureChannelIDInvalid                                       StatusCode = 0x80220000 // The specified secure channel is no longer valid.
	StatusCode_BadInvalidTimestamp                                             StatusCode = 0x80230000 // The timestamp is outside the range allowed by the server.
	StatusCode_BadNonceInvalid                                                 StatusCode = 0x80240000 // The nonce does appear to be not a random value or it is not the correct length.
	StatusCode_BadSessionIDInvalid                                             StatusCode = 0x80250000 // The session id is not valid.
	StatusCode_BadSessionClosed                                                StatusCode = 0x80260000 // The session was closed by the client.
	StatusCode_BadSessionNotActivated                                          StatusCode = 0x80270000 // The session cannot be used because ActivateSession has not been called.
	StatusCode_BadSubscriptionIDInvalid                                        StatusCode = 0x80280000 // The subscription id is not valid.
	StatusCode_BadRequestHeaderInvalid                                         StatusCode = 0x802A0000 // The header for the request is missing or invalid.
	StatusCode_BadTimestampsToReturnInvalid                                    StatusCode = 0x802B0000 // The timestamps to return parameter is invalid.
	StatusCode_BadRequestCancelledByClient                                     StatusCode = 0x802C0000 // The request was cancelled by the client.
	StatusCode_BadTooManyArguments                                             StatusCode = 0x80E50000 // Too many arguments were provided.
	StatusCode_BadLicenseExpired                                               StatusCode = 0x810E0000 // The server requires a license to operate in general or to perform a service or operatio
	StatusCode_BadLicenseLimitsExceeded                                        StatusCode = 0x810F0000 // The server has limits on number of allowed operations / object
	StatusCode_BadLicenseNotAvailable                                          StatusCode = 0x81100000 // The server does not have a license which is required to operate in general or to perform a service or operation.
	StatusCode_GoodSubscriptionTransferred                                     StatusCode = 0x002D0000 // The subscription was transferred to another session.
	StatusCode_GoodCompletesAsynchronously                                     StatusCode = 0x002E0000 // The processing will complete asynchronously.
	StatusCode_GoodOverload                                                    StatusCode = 0x002F0000 // Sampling has slowed down due to resource limitations.
	StatusCode_GoodClamped                                                     StatusCode = 0x00300000 // The value written was accepted but was clamped.
	StatusCode_BadNoCommunication                                              StatusCode = 0x80310000 // Communication with the data source is define
	StatusCode_BadWaitingForInitialData                                        StatusCode = 0x80320000 // Waiting for the server to obtain values from the underlying data source.
	StatusCode_BadNodeIDInvalid                                                StatusCode = 0x80330000 // The syntax of the node id is not valid.
	StatusCode_BadNodeIDUnknown                                                StatusCode = 0x80340000 // The node id refers to a node that does not exist in the server address space.
	StatusCode_BadAttributeIDInvalid                                           StatusCode = 0x80350000 // The attribute is not supported for the specified Node.
	StatusCode_BadIndexRangeInvalid                                            StatusCode = 0x80360000 // The syntax of the index range parameter is invalid.
	StatusCode_BadIndexRangeNoData                                             StatusCode = 0x80370000 // No data exists within the range of indexes specified.
	StatusCode_BadDataEncodingInvalid                                          StatusCode = 0x80380000 // The data encoding is invalid.
	StatusCode_BadDataEncodingUnsupported                                      StatusCode = 0x80390000 // The server does not support the requested data encoding for the node.
	StatusCode_BadNotReadable                                                  StatusCode = 0x803A0000 // The access level does not allow reading or subscribing to the Node.
	StatusCode_BadNotWritable                                                  StatusCode = 0x803B0000 // The access level does not allow writing to the Node.
	StatusCode_BadOutOfRange                                                   StatusCode = 0x803C0000 // The value was out of range.
	StatusCode_BadNotSupported                                                 StatusCode = 0x803D0000 // The requested operation is not supported.
	StatusCode_BadNotFound                                                     StatusCode = 0x803E0000 // A requested item was not found or a search operation ended without success.
	StatusCode_BadObjectDeleted                                                StatusCode = 0x803F0000 // The object cannot be used because it has been deleted.
	StatusCode_BadNotImplemented                                               StatusCode = 0x80400000 // Requested operation is not implemented.
	StatusCode_BadMonitoringModeInvalid                                        StatusCode = 0x80410000 // The monitoring mode is invalid.
	StatusCode_BadMonitoredItemIDInvalid                                       StatusCode = 0x80420000 // The monitoring item id does not refer to a valid monitored item.
	StatusCode_BadMonitoredItemFilterInvalid                                   StatusCode = 0x80430000 // The monitored item filter parameter is not valid.
	StatusCode_BadMonitoredItemFilterUnsupported                               StatusCode = 0x80440000 // The server does not support the requested monitored item filter.
	StatusCode_BadFilterNotAllowed                                             StatusCode = 0x80450000 // A monitoring filter cannot be used in combination with the attribute specified.
	StatusCode_BadStructureMissing                                             StatusCode = 0x80460000 // A mandatory structured parameter was missing or null.
	StatusCode_BadEventFilterInvalid                                           StatusCode = 0x80470000 // The event filter is not valid.
	StatusCode_BadContentFilterInvalid                                         StatusCode = 0x80480000 // The content filter is not valid.
	StatusCode_BadFilterOperatorInvalid                                        StatusCode = 0x80C10000 // An unrecognized operator was provided in a filter.
	StatusCode_BadFilterOperatorUnsupported                                    StatusCode = 0x80C20000 // A valid operator was provide
	StatusCode_BadFilterOperandCountMismatch                                   StatusCode = 0x80C30000 // The number of operands provided for the filter operator was less then expected for the operand provided.
	StatusCode_BadFilterOperandInvalid                                         StatusCode = 0x80490000 // The operand used in a content filter is not valid.
	StatusCode_BadFilterElementInvalid                                         StatusCode = 0x80C40000 // The referenced element is not a valid element in the content filter.
	StatusCode_BadFilterLiteralInvalid                                         StatusCode = 0x80C50000 // The referenced literal is not a valid value.
	StatusCode_BadContinuationPointInvalid                                     StatusCode = 0x804A0000 // The continuation point provide is longer valid.
	StatusCode_BadNoContinuationPoints                                         StatusCode = 0x804B0000 // The operation could not be processed because all continuation points have been allocated.
	StatusCode_BadReferenceTypeIDInvalid                                       StatusCode = 0x804C0000 // The reference type id does not refer to a valid reference type node.
	StatusCode_BadBrowseDirectionInvalid                                       StatusCode = 0x804D0000 // The browse direction is not valid.
	StatusCode_BadNodeNotInView                                                StatusCode = 0x804E0000 // The node is not part of the view.
	StatusCode_BadNumericOverflow                                              StatusCode = 0x81120000 // The number was not accepted because of a numeric overflow.
	StatusCode_BadServerURIInvalid                                             StatusCode = 0x804F0000 // The ServerUri is not a valid URI.
	StatusCode_BadServerNameMissing                                            StatusCode = 0x80500000 // No ServerName was specified.
	StatusCode_BadDiscoveryURLMissing                                          StatusCode = 0x80510000 // No DiscoveryURL was specified.
	StatusCode_BadSemaphoreFileMissing                                         StatusCode = 0x80520000 // The semaphore file specified by the client is not valid.
	StatusCode_BadRequestTypeInvalid                                           StatusCode = 0x80530000 // The security token request type is not valid.
	StatusCode_BadSecurityModeRejected                                         StatusCode = 0x80540000 // The security mode does not meet the requirements set by the server.
	StatusCode_BadSecurityPolicyRejected                                       StatusCode = 0x80550000 // The security policy does not meet the requirements set by the server.
	StatusCode_BadTooManySessions                                              StatusCode = 0x80560000 // The server has reached its maximum number of sessions.
	StatusCode_BaduserSignatureInvalid                                         StatusCode = 0x80570000 // The user token signature is missing or invalid.
	StatusCode_BadApplicationSignatureInvalid                                  StatusCode = 0x80580000 // The signature generated with the client certificate is missing or invalid.
	StatusCode_BadnovalIDCertificates                                          StatusCode = 0x80590000 // The client did not provide at least one software certificate that is valid and meets the profile requirements for the server.
	StatusCode_BadIdentitychangeNotSupported                                   StatusCode = 0x80C60000 // The server does not support changing the user identity assigned to the session.
	StatusCode_BadRequestcancelledbyRequest                                    StatusCode = 0x805A0000 // The request was cancelled by the client with the Cancel service.
	StatusCode_BadParentNodeIDInvalid                                          StatusCode = 0x805B0000 // The parent node id does not to refer to a valid node.
	StatusCode_BadReferenceNotAllowed                                          StatusCode = 0x805C0000 // The reference could not be created because it violates constraints imposed by the data model.
	StatusCode_BadNodeIDRejected                                               StatusCode = 0x805D0000 // The requested node id was reject because it was either invalid or server does not allow node ids to be specified by the client.
	StatusCode_BadNodeIDExists                                                 StatusCode = 0x805E0000 // The requested node id is already used by another node.
	StatusCode_BadNodeClassInvalid                                             StatusCode = 0x805F0000 // The node class is not valid.
	StatusCode_BadBrowseNameInvalid                                            StatusCode = 0x80600000 // The browse name is invalid.
	StatusCode_BadBrowseNameduplicated                                         StatusCode = 0x80610000 // The browse name is not unique among nodes that share the same relationship with the parent.
	StatusCode_BadNodeAttributesInvalid                                        StatusCode = 0x80620000 // The node attributes are not valid for the node class.
	StatusCode_BadTypedefinitionInvalid                                        StatusCode = 0x80630000 // The type definition node id does not reference an appropriate type node.
	StatusCode_BadsourceNodeIDInvalid                                          StatusCode = 0x80640000 // The source node id does not reference a valid node.
	StatusCode_BadtargetNodeIDInvalid                                          StatusCode = 0x80650000 // The target node id does not reference a valid node.
	StatusCode_BadduplicateReferenceNotAllowed                                 StatusCode = 0x80660000 // The reference type between the nodes is already defined.
	StatusCode_BadInvalidselfReference                                         StatusCode = 0x80670000 // The server does not allow this type of self reference on this node.
	StatusCode_BadReferenceLocalonly                                           StatusCode = 0x80680000 // The reference type is not valid for a reference to a remote server.
	StatusCode_BadNodeleterights                                               StatusCode = 0x80690000 // The server will not allow the node to be deleted.
	StatusCode_UncertainReferenceNotDeleted                                    StatusCode = 0x40BC0000 // The server was not able to delete all target references.
	StatusCode_BadServerIndexInvalid                                           StatusCode = 0x806A0000 // The server index is not valid.
	StatusCode_BadViewIDUnknown                                                StatusCode = 0x806B0000 // The view id does not refer to a valid view node.
	StatusCode_BadViewTimestampInvalid                                         StatusCode = 0x80C90000 // The view timestamp is not available or not supported.
	StatusCode_BadViewparameterMismatch                                        StatusCode = 0x80CA0000 // The view parameters are not consistent with each other.
	StatusCode_BadViewVersionInvalid                                           StatusCode = 0x80CB0000 // The view version is not available or not supported.
	StatusCode_UncertainNotallNodesAvailable                                   StatusCode = 0x40C00000 // The list of references may not be complete because the underlying system is not available.
	StatusCode_GoodresultsmaybeInComplete                                      StatusCode = 0x00BA0000 // The server should have followed a reference to a node in a remote server but did not. The result set may be incomplete.
	StatusCode_BadNotTypedefinition                                            StatusCode = 0x80C80000 // The provided Nodeid was not a type definition nodeid.
	StatusCode_UncertainReferenceOutOfServer                                   StatusCode = 0x406C0000 // One of the references to follow in the relative path references to a node in the address space in another server.
	StatusCode_BadTooManymatches                                               StatusCode = 0x806D0000 // The requested operation has too many matches to return.
	StatusCode_BadqueryToocomplex                                              StatusCode = 0x806E0000 // The requested operation requires too many resources in the server.
	StatusCode_Badnomatch                                                      StatusCode = 0x806F0000 // The requested operation has no match to return.
	StatusCode_BadMaxageInvalid                                                StatusCode = 0x80700000 // The max age parameter is invalid.
	StatusCode_BadSecurityModeInsufficient                                     StatusCode = 0x80E60000 // The operation is not permitted over the current secure channel.
	StatusCode_BadhistoryOperationInvalid                                      StatusCode = 0x80710000 // The history details parameter is not valid.
	StatusCode_BadhistoryOperationUnsupported                                  StatusCode = 0x80720000 // The server does not support the requested operation.
	StatusCode_BadInvalidTimestampArgument                                     StatusCode = 0x80BD0000 // The defined timestamp to return was invalid.
	StatusCode_BadWriteNotSupported                                            StatusCode = 0x80730000 // The server does not support writing the combination of valu
	StatusCode_BadTypeMismatch                                                 StatusCode = 0x80740000 // The value supplied for the attribute is not of the same type as the attribute's value.
	StatusCode_BadMethodInvalid                                                StatusCode = 0x80750000 // The method id does not refer to a method for the specified object.
	StatusCode_BadArgumentsMissing                                             StatusCode = 0x80760000 // The client did not specify all of the input arguments for the method.
	StatusCode_BadNotExecutable                                                StatusCode = 0x81110000 // The executable attribute does not allow the execution of the method.
	StatusCode_BadTooManySubscriptions                                         StatusCode = 0x80770000 // The server has reached its maximum number of subscriptions.
	StatusCode_BadTooManyPublishRequests                                       StatusCode = 0x80780000 // The server has reached the maximum number of queued publish requests.
	StatusCode_BadNoSubscription                                               StatusCode = 0x80790000 // There is no subscription available for this session.
	StatusCode_BadSequenceNumberUnknown                                        StatusCode = 0x807A0000 // The sequence number is unknown to the server.
	StatusCode_GoodRetransmissionQueueNotSupported                             StatusCode = 0x00DF0000 // The Server does not support retransmission queue and acknowledgement of sequence numbers is not available.
	StatusCode_BadMessageNotAvailable                                          StatusCode = 0x807B0000 // The requested notification message is no longer available.
	StatusCode_BadinsufficientclientProfile                                    StatusCode = 0x807C0000 // The client of the current session does not support one or more Profiles that are necessary for the subscription.
	StatusCode_BadStateNotActive                                               StatusCode = 0x80BF0000 // The sub-state machine is not currently active.
	StatusCode_BadAlreadyExists                                                StatusCode = 0x81150000 // An equivalent rule already exists.
	StatusCode_BadTCPServerTooBusy                                             StatusCode = 0x807D0000 // The server cannot process the request because it is too busy.
	StatusCode_BadTCPMessageTypeInvalid                                        StatusCode = 0x807E0000 // The type of the message specified in the header invalid.
	StatusCode_BadTCPSecureChannelUnknown                                      StatusCode = 0x807F0000 // The SecureChannelId and/or TokenId are not currently in use.
	StatusCode_BadTCPMessageTooLarge                                           StatusCode = 0x80800000 // The size of the message chunk specified in the header is too large.
	StatusCode_BadTCPNotEnoughResources                                        StatusCode = 0x80810000 // There are not enough resources to process the request.
	StatusCode_BadTCPInternalError                                             StatusCode = 0x80820000 // An internal error occurred.
	StatusCode_BadTCPendPointURLInvalid                                        StatusCode = 0x80830000 // The server does not recognize the QueryString specified.
	StatusCode_BadRequestInterrupted                                           StatusCode = 0x80840000 // The request could not be sent because of a network interruption.
	StatusCode_BadRequestTimeout                                               StatusCode = 0x80850000 // Timeout occurred while processing the request.
	StatusCode_BadSecureChannelClosed                                          StatusCode = 0x80860000 // The secure channel has been closed.
	StatusCode_BadSecureChannelTokenUnknown                                    StatusCode = 0x80870000 // The token has expired or is not recognized.
	StatusCode_BadSequenceNumberInvalid                                        StatusCode = 0x80880000 // The sequence number is not valid.
	StatusCode_BadProtocolVersionUnsupported                                   StatusCode = 0x80BE0000 // The applications do not have compatible protocol versions.
	StatusCode_BadConfigurationError                                           StatusCode = 0x80890000 // There is a problem with the configuration that affects the usefulness of the value.
	StatusCode_BadNotConnected                                                 StatusCode = 0x808A0000 // The variable should receive its value from another variabl
	StatusCode_BadDeviceFailure                                                StatusCode = 0x808B0000 // There has been a failure in the device/data source that generates the value that has affected the value.
	StatusCode_BadSensorFailure                                                StatusCode = 0x808C0000 // There has been a failure in the sensor from which the value is derived by the device/data source.
	StatusCode_BadOutOfService                                                 StatusCode = 0x808D0000 // The source of the data is not operational.
	StatusCode_BadDeadbandFilterInvalid                                        StatusCode = 0x808E0000 // The deadband filter is not valid.
	StatusCode_UncertainNoCommunicationLastUsableValue                         StatusCode = 0x408F0000 // Communication to the data source has failed. The variable value is the last value that had a good quality.
	StatusCode_UncertainLastUsableValue                                        StatusCode = 0x40900000 // Whatever was updating this value has stopped doing so.
	StatusCode_UncertainSubstituteValue                                        StatusCode = 0x40910000 // The value is an operational value that was manually overwritten.
	StatusCode_UncertainInitialValue                                           StatusCode = 0x40920000 // The value is an initial value for a variable that normally receives its value from another variable.
	StatusCode_UncertainSensorNotAccurate                                      StatusCode = 0x40930000 // The value is at one of the sensor limits.
	StatusCode_UncertainEngineeringUnitsExceeded                               StatusCode = 0x40940000 // The value is outside of the range of values defined for this parameter.
	StatusCode_UncertainSubnormal                                              StatusCode = 0x40950000 // The value is derived from multiple sources and has less than the required number of Good sources.
	StatusCode_GoodLocalOverride                                               StatusCode = 0x00960000 // The value has been overridden.
	StatusCode_BadRefreshInProgress                                            StatusCode = 0x80970000 // This Condition refresh faile
	StatusCode_BadConditionAlreadyDisabled                                     StatusCode = 0x80980000 // This condition has already been disabled.
	StatusCode_BadConditionAlreadyenabled                                      StatusCode = 0x80CC0000 // This condition has already been enabled.
	StatusCode_BadConditionDisabled                                            StatusCode = 0x80990000 // Property not availabl
	StatusCode_BadEventIDUnknown                                               StatusCode = 0x809A0000 // The specified event id is not recognized.
	StatusCode_BadEventNotAcknowledgeable                                      StatusCode = 0x80BB0000 // The event cannot be acknowledged.
	StatusCode_BadDialogNotActive                                              StatusCode = 0x80CD0000 // The dialog condition is not active.
	StatusCode_BadDialogResponseInvalid                                        StatusCode = 0x80CE0000 // The response is not valid for the dialog.
	StatusCode_BadConditionBranchAlreadyAcked                                  StatusCode = 0x80CF0000 // The condition branch has already been acknowledged.
	StatusCode_BadConditionBranchAlreadyConfirmed                              StatusCode = 0x80D00000 // The condition branch has already been confirmed.
	StatusCode_BadConditionAlreadyShelved                                      StatusCode = 0x80D10000 // The condition has already been shelved.
	StatusCode_BadConditionNotShelved                                          StatusCode = 0x80D20000 // The condition is not currently shelved.
	StatusCode_BadShelvingTimeOutOfRange                                       StatusCode = 0x80D30000 // The shelving time not within an acceptable range.
	StatusCode_BadNoData                                                       StatusCode = 0x809B0000 // No data exists for the requested time range or event filter.
	StatusCode_BadBoundNotFound                                                StatusCode = 0x80D70000 // No data found to provide upper or lower bound value.
	StatusCode_BadBoundNotSupported                                            StatusCode = 0x80D80000 // The server cannot retrieve a bound for the variable.
	StatusCode_BadDataLost                                                     StatusCode = 0x809D0000 // Data is missing due to collection started/stopped/lost.
	StatusCode_BadDataUnavailable                                              StatusCode = 0x809E0000 // Expected data is unavailable for the requested time range due to an un-mounted volum
	StatusCode_BadEntryExists                                                  StatusCode = 0x809F0000 // The data or event was not successfully inserted because a matching entry exists.
	StatusCode_BadNoEntryExists                                                StatusCode = 0x80A00000 // The data or event was not successfully updated because no matching entry exists.
	StatusCode_BadTimestampNotSupported                                        StatusCode = 0x80A10000 // The client requested history using a timestamp format the server does not support (i.e requested ServerTimestamp when server only supports SourceTimestamp).
	StatusCode_GoodEntryInserted                                               StatusCode = 0x00A20000 // The data or event was successfully inserted into the historical database.
	StatusCode_GoodEntryReplaced                                               StatusCode = 0x00A30000 // The data or event field was successfully replaced in the historical database.
	StatusCode_UncertainDataSubnormal                                          StatusCode = 0x40A40000 // The value is derived from multiple values and has less than the required number of Good values.
	StatusCode_GoodNoData                                                      StatusCode = 0x00A50000 // No data exists for the requested time range or event filter.
	StatusCode_GoodMoreData                                                    StatusCode = 0x00A60000 // More data is available in the time range beyond the number of values requested.
	StatusCode_BadAggregateListMismatch                                        StatusCode = 0x80D40000 // The requested number of Aggregates does not match the requested number of NodeIds.
	StatusCode_BadAggregateNotSupported                                        StatusCode = 0x80D50000 // The requested Aggregate is not support by the server.
	StatusCode_BadAggregateInvalidInputs                                       StatusCode = 0x80D60000 // The aggregate value could not be derived due to invalid data inputs.
	StatusCode_BadAggregateConfigurationRejected                               StatusCode = 0x80DA0000 // The aggregate configuration is not valid for specified node.
	StatusCode_GoodDataIgnored                                                 StatusCode = 0x00D90000 // The request specifies fields which are not valid for the EventType or cannot be saved by the historian.
	StatusCode_BadRequestNotAllowed                                            StatusCode = 0x80E40000 // The request was rejected by the server because it did not meet the criteria set by the server.
	StatusCode_BadRequestNotComplete                                           StatusCode = 0x81130000 // The request has not been processed by the server yet.
	StatusCode_BadTransactionPending                                           StatusCode = 0x80E80000 // The operation is not allowed because a transaction is in progress.
	StatusCode_BadTicketRequired                                               StatusCode = 0x811F0000 // The device identity needs a ticket before it can be accepted.
	StatusCode_BadTicketInvalid                                                StatusCode = 0x81200000 // The device identity needs a ticket before it can be accepted.
	StatusCode_BadLocked                                                       StatusCode = 0x80E90000 // The requested operation is not allowed
	StatusCode_GoodEdited                                                      StatusCode = 0x00DC0000 // The value does not come from the real source and has been edited by the server.
	StatusCode_GoodPostActionFailed                                            StatusCode = 0x00DD0000 // There was an error in execution of these post-actions.
	StatusCode_UncertainDominantValueChanged                                   StatusCode = 0x40DE0000 // The related EngineeringUnit has been changed but the Variable Value is still provided based on the previous unit.
	StatusCode_GoodDependentValueChanged                                       StatusCode = 0x00E00000 // A dependent value has been changed but the change has not been applied to the device.
	StatusCode_BadDominantValueChanged                                         StatusCode = 0x80E10000 // The related EngineeringUnit has been changed but this change has not been applied to the device. The Variable Value is still dependent on the previous unit but its status is currently Bad.
	StatusCode_UncertainDependentValueChanged                                  StatusCode = 0x40E20000 // A dependent value has been changed but the change has not been applied to the device. The quality of the dominant variable is uncertain.
	StatusCode_BadDependentValueChanged                                        StatusCode = 0x80E30000 // A dependent value has been changed but the change has not been applied to the device. The quality of the dominant variable is Bad.
	StatusCode_GoodEdited_DependentValueChanged                                StatusCode = 0x01160000 // It is delivered with a dominant Variable value when a dependent Variable has changed but the change has not been applied.
	StatusCode_GoodEdited_DominantValueChanged                                 StatusCode = 0x01170000 // It is delivered with a dependent Variable value when a dominant Variable has changed but the change has not been applied.
	StatusCode_GoodEdited_DominantValueChanged_DependentValueChanged           StatusCode = 0x01180000 // It is delivered with a dependent Variable value when a dominant or dependent Variable has changed but change has not been applied.
	StatusCode_BadEdited_OutOfRange                                            StatusCode = 0x81190000 // It is delivered with a Variable value when Variable has changed but the value is not legal.
	StatusCode_BadInitialValue_OutOfRange                                      StatusCode = 0x811A0000 // It is delivered with a Variable value when a source Variable has changed but the value is not legal.
	StatusCode_BadOutOfRange_DominantValueChanged                              StatusCode = 0x811B0000 // It is delivered with a dependent Variable value when a dominant Variable has changed and the value is not legal.
	StatusCode_BadEdited_OutOfRange_DominantValueChanged                       StatusCode = 0x811C0000 // It is delivered with a dependent Variable value when a dominant Variable has change
	StatusCode_BadOutOfRange_DominantValueChanged_DependentValueChanged        StatusCode = 0x811D0000 // It is delivered with a dependent Variable value when a dominant or dependent Variable has changed and the value is not legal.
	StatusCode_BadEdited_OutOfRange_DominantValueChanged_DependentValueChanged StatusCode = 0x811E0000 // It is delivered with a dependent Variable value when a dominant or dependent Variable has change
	StatusCode_GoodCommunicationEvent                                          StatusCode = 0x00A70000 // The communication layer has raised an event.
	StatusCode_GoodShutdownEvent                                               StatusCode = 0x00A80000 // The system is shutting down.
	StatusCode_GoodCallAgain                                                   StatusCode = 0x00A90000 // The operation is not finished and needs to be called again.
	StatusCode_GoodNonCriticalTimeout                                          StatusCode = 0x00AA0000 // A non-critical timeout occurred.
	StatusCode_BadInvalidArgument                                              StatusCode = 0x80AB0000 // One or more arguments are invalid.
	StatusCode_BadConnectionRejected                                           StatusCode = 0x80AC0000 // Could not establish a network connection to remote server.
	StatusCode_BadDisconnect                                                   StatusCode = 0x80AD0000 // The server has disconnected from the client.
	StatusCode_BadConnectionClosed                                             StatusCode = 0x80AE0000 // The network connection has been closed.
	StatusCode_BadInvalidState                                                 StatusCode = 0x80AF0000 // The operation cannot be completed because the object is close
	StatusCode_BadEndOfStream                                                  StatusCode = 0x80B00000 // Cannot move beyond end of the stream.
	StatusCode_BadNoDataAvailable                                              StatusCode = 0x80B10000 // No data is currently available for reading from a non-blocking stream.
	StatusCode_BadWaitingForResponse                                           StatusCode = 0x80B20000 // The asynchronous operation is waiting for a response.
	StatusCode_BadOperationAbandoned                                           StatusCode = 0x80B30000 // The asynchronous operation was abandoned by the caller.
	StatusCode_BadExpectedStreamToBlock                                        StatusCode = 0x80B40000 // The stream did not return all data requested (possibly because it is a non-blocking stream).
	StatusCode_BadWouldBlock                                                   StatusCode = 0x80B50000 // Non blocking behaviour is required and the operation would block.
	StatusCode_BadSyntaxError                                                  StatusCode = 0x80B60000 // A value had an invalid syntax.
	StatusCode_BadMaxConnectionsReached                                        StatusCode = 0x80B70000 // The operation could not be finished because all available connections are in use.
	StatusCode_UncertainTransducerInManual                                     StatusCode = 0x42080000 // The value may not be accurate because the transducer is in manual mode.
	StatusCode_UncertainSimulatedValue                                         StatusCode = 0x42090000 // The value is simulated.
	StatusCode_UncertainSensorCalibration                                      StatusCode = 0x420A0000 // The value may not be accurate due to a sensor calibration fault.
	StatusCode_UncertainConfigurationError                                     StatusCode = 0x420F0000 // The value may not be accurate due to a configuration issue.
	StatusCode_GoodCascadeInitializationAcknowledged                           StatusCode = 0x04010000 // The value source supports cascade handshaking and the value has been Initialized based on an initialization request from a cascade secondary.
	StatusCode_GoodCascadeInitializationRequest                                StatusCode = 0x04020000 // The value source supports cascade handshaking and is requesting initialization of a cascade primary.
	StatusCode_GoodCascadeNotInvited                                           StatusCode = 0x04030000 // The value source supports cascade handshakin
	StatusCode_GoodCascadeNotSelected                                          StatusCode = 0x04040000 // The value source supports cascade handshakin
	StatusCode_GoodFaultStateActive                                            StatusCode = 0x04070000 // There is a fault state condition active in the value source.
	StatusCode_GoodInitiateFaultState                                          StatusCode = 0x04080000 // A fault state condition is being requested of the destination.
	StatusCode_GoodCascade                                                     StatusCode = 0x04090000 // The value is accurat
	StatusCode_BadDataSetIDInvalid                                             StatusCode = 0x80E70000 // The DataSet specified for the DataSetWriter creation is invalid.

)
